apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi

resources:
  - ../../base

# Image tag replaced by the CI/CD (deploy workflow).
images:
  - name: ghcr.io/julienau/multi
    newTag: latest
